---
# ServiceAccount for our app.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cool-kube
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cool-kube
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# Bind "cool-kube" Role to "cool-kube" ServiceAccount.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cool-kube
  namespace: default # This only grants permissions within the "default" namespace.
subjects:
- kind: ServiceAccount
  name: cool-kube 
  apiGroup: ""
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: cool-kube # this must match the name of the Role or ClusterRole you wish to bind to.
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cool-kube
  labels:
    app: cool-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cool-kube
  template:
    metadata:
      labels:
        app: cool-kube
    spec:
      serviceAccount: cool-kube
      containers:
      - name: cool-kube
        image: localhost:5000/cool-kube:v1
        imagePullPolicy: Always
